// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/api_platform_topSecret.proto

package com.akaxin.proto.platform;

public final class ApiPlatformTopSecretProto {
  private ApiPlatformTopSecretProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ApiPlatformTopSecretRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiPlatformTopSecretRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *站点地址
     * </pre>
     *
     * <code>optional string site_host = 1;</code>
     */
    String getSiteHost();
    /**
     * <pre>
     *站点地址
     * </pre>
     *
     * <code>optional string site_host = 1;</code>
     */
    com.google.protobuf.ByteString
        getSiteHostBytes();

    /**
     * <pre>
     *站点端口号
     * </pre>
     *
     * <code>optional string site_port = 2;</code>
     */
    String getSitePort();
    /**
     * <pre>
     *站点端口号
     * </pre>
     *
     * <code>optional string site_port = 2;</code>
     */
    com.google.protobuf.ByteString
        getSitePortBytes();
  }
  /**
   * Protobuf type {@code site.ApiPlatformTopSecretRequest}
   */
  public  static final class ApiPlatformTopSecretRequest extends
      com.google.protobuf.GeneratedMessageLite<
          ApiPlatformTopSecretRequest, ApiPlatformTopSecretRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:site.ApiPlatformTopSecretRequest)
      ApiPlatformTopSecretRequestOrBuilder {
    private ApiPlatformTopSecretRequest() {
      siteHost_ = "";
      sitePort_ = "";
    }
    public static final int SITE_HOST_FIELD_NUMBER = 1;
    private String siteHost_;
    /**
     * <pre>
     *站点地址
     * </pre>
     *
     * <code>optional string site_host = 1;</code>
     */
    public String getSiteHost() {
      return siteHost_;
    }
    /**
     * <pre>
     *站点地址
     * </pre>
     *
     * <code>optional string site_host = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSiteHostBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(siteHost_);
    }
    /**
     * <pre>
     *站点地址
     * </pre>
     *
     * <code>optional string site_host = 1;</code>
     */
    private void setSiteHost(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      siteHost_ = value;
    }
    /**
     * <pre>
     *站点地址
     * </pre>
     *
     * <code>optional string site_host = 1;</code>
     */
    private void clearSiteHost() {

      siteHost_ = getDefaultInstance().getSiteHost();
    }
    /**
     * <pre>
     *站点地址
     * </pre>
     *
     * <code>optional string site_host = 1;</code>
     */
    private void setSiteHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      siteHost_ = value.toStringUtf8();
    }

    public static final int SITE_PORT_FIELD_NUMBER = 2;
    private String sitePort_;
    /**
     * <pre>
     *站点端口号
     * </pre>
     *
     * <code>optional string site_port = 2;</code>
     */
    public String getSitePort() {
      return sitePort_;
    }
    /**
     * <pre>
     *站点端口号
     * </pre>
     *
     * <code>optional string site_port = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSitePortBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sitePort_);
    }
    /**
     * <pre>
     *站点端口号
     * </pre>
     *
     * <code>optional string site_port = 2;</code>
     */
    private void setSitePort(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      sitePort_ = value;
    }
    /**
     * <pre>
     *站点端口号
     * </pre>
     *
     * <code>optional string site_port = 2;</code>
     */
    private void clearSitePort() {

      sitePort_ = getDefaultInstance().getSitePort();
    }
    /**
     * <pre>
     *站点端口号
     * </pre>
     *
     * <code>optional string site_port = 2;</code>
     */
    private void setSitePortBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      sitePort_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!siteHost_.isEmpty()) {
        output.writeString(1, getSiteHost());
      }
      if (!sitePort_.isEmpty()) {
        output.writeString(2, getSitePort());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!siteHost_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSiteHost());
      }
      if (!sitePort_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getSitePort());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code site.ApiPlatformTopSecretRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApiPlatformTopSecretRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiPlatformTopSecretRequest)
        com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequestOrBuilder {
      // Construct using com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *站点地址
       * </pre>
       *
       * <code>optional string site_host = 1;</code>
       */
      public String getSiteHost() {
        return instance.getSiteHost();
      }
      /**
       * <pre>
       *站点地址
       * </pre>
       *
       * <code>optional string site_host = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSiteHostBytes() {
        return instance.getSiteHostBytes();
      }
      /**
       * <pre>
       *站点地址
       * </pre>
       *
       * <code>optional string site_host = 1;</code>
       */
      public Builder setSiteHost(
          String value) {
        copyOnWrite();
        instance.setSiteHost(value);
        return this;
      }
      /**
       * <pre>
       *站点地址
       * </pre>
       *
       * <code>optional string site_host = 1;</code>
       */
      public Builder clearSiteHost() {
        copyOnWrite();
        instance.clearSiteHost();
        return this;
      }
      /**
       * <pre>
       *站点地址
       * </pre>
       *
       * <code>optional string site_host = 1;</code>
       */
      public Builder setSiteHostBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSiteHostBytes(value);
        return this;
      }

      /**
       * <pre>
       *站点端口号
       * </pre>
       *
       * <code>optional string site_port = 2;</code>
       */
      public String getSitePort() {
        return instance.getSitePort();
      }
      /**
       * <pre>
       *站点端口号
       * </pre>
       *
       * <code>optional string site_port = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSitePortBytes() {
        return instance.getSitePortBytes();
      }
      /**
       * <pre>
       *站点端口号
       * </pre>
       *
       * <code>optional string site_port = 2;</code>
       */
      public Builder setSitePort(
          String value) {
        copyOnWrite();
        instance.setSitePort(value);
        return this;
      }
      /**
       * <pre>
       *站点端口号
       * </pre>
       *
       * <code>optional string site_port = 2;</code>
       */
      public Builder clearSitePort() {
        copyOnWrite();
        instance.clearSitePort();
        return this;
      }
      /**
       * <pre>
       *站点端口号
       * </pre>
       *
       * <code>optional string site_port = 2;</code>
       */
      public Builder setSitePortBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSitePortBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:site.ApiPlatformTopSecretRequest)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest other = (com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest) arg1;
          siteHost_ = visitor.visitString(!siteHost_.isEmpty(), siteHost_,
              !other.siteHost_.isEmpty(), other.siteHost_);
          sitePort_ = visitor.visitString(!sitePort_.isEmpty(), sitePort_,
              !other.sitePort_.isEmpty(), other.sitePort_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  siteHost_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  sitePort_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:site.ApiPlatformTopSecretRequest)
    private static final com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApiPlatformTopSecretRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApiPlatformTopSecretRequest> PARSER;

    public static com.google.protobuf.Parser<ApiPlatformTopSecretRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ApiPlatformTopSecretResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiPlatformTopSecretResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *平台是否针对站点开启该站点开启绝密功能
     * </pre>
     *
     * <code>optional bool open_top_secret = 1;</code>
     */
    boolean getOpenTopSecret();
  }
  /**
   * Protobuf type {@code site.ApiPlatformTopSecretResponse}
   */
  public  static final class ApiPlatformTopSecretResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ApiPlatformTopSecretResponse, ApiPlatformTopSecretResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:site.ApiPlatformTopSecretResponse)
      ApiPlatformTopSecretResponseOrBuilder {
    private ApiPlatformTopSecretResponse() {
    }
    public static final int OPEN_TOP_SECRET_FIELD_NUMBER = 1;
    private boolean openTopSecret_;
    /**
     * <pre>
     *平台是否针对站点开启该站点开启绝密功能
     * </pre>
     *
     * <code>optional bool open_top_secret = 1;</code>
     */
    public boolean getOpenTopSecret() {
      return openTopSecret_;
    }
    /**
     * <pre>
     *平台是否针对站点开启该站点开启绝密功能
     * </pre>
     *
     * <code>optional bool open_top_secret = 1;</code>
     */
    private void setOpenTopSecret(boolean value) {

      openTopSecret_ = value;
    }
    /**
     * <pre>
     *平台是否针对站点开启该站点开启绝密功能
     * </pre>
     *
     * <code>optional bool open_top_secret = 1;</code>
     */
    private void clearOpenTopSecret() {

      openTopSecret_ = false;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (openTopSecret_ != false) {
        output.writeBool(1, openTopSecret_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (openTopSecret_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, openTopSecret_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code site.ApiPlatformTopSecretResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApiPlatformTopSecretResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiPlatformTopSecretResponse)
        com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponseOrBuilder {
      // Construct using com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *平台是否针对站点开启该站点开启绝密功能
       * </pre>
       *
       * <code>optional bool open_top_secret = 1;</code>
       */
      public boolean getOpenTopSecret() {
        return instance.getOpenTopSecret();
      }
      /**
       * <pre>
       *平台是否针对站点开启该站点开启绝密功能
       * </pre>
       *
       * <code>optional bool open_top_secret = 1;</code>
       */
      public Builder setOpenTopSecret(boolean value) {
        copyOnWrite();
        instance.setOpenTopSecret(value);
        return this;
      }
      /**
       * <pre>
       *平台是否针对站点开启该站点开启绝密功能
       * </pre>
       *
       * <code>optional bool open_top_secret = 1;</code>
       */
      public Builder clearOpenTopSecret() {
        copyOnWrite();
        instance.clearOpenTopSecret();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:site.ApiPlatformTopSecretResponse)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse other = (com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse) arg1;
          openTopSecret_ = visitor.visitBoolean(openTopSecret_ != false, openTopSecret_,
              other.openTopSecret_ != false, other.openTopSecret_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  openTopSecret_ = input.readBool();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:site.ApiPlatformTopSecretResponse)
    private static final com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApiPlatformTopSecretResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.akaxin.proto.platform.ApiPlatformTopSecretProto.ApiPlatformTopSecretResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApiPlatformTopSecretResponse> PARSER;

    public static com.google.protobuf.Parser<ApiPlatformTopSecretResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
