// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/file.proto

package com.akaxin.proto.core;

public final class FileProto {
  private FileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code core.FileType}
   */
  public enum FileType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     * 未知的文件类型类型
     * </pre>
     *
     * <code>UNKNOWN_FILE = 0;</code>
     */
    UNKNOWN_FILE(0),
    /**
     * <pre>
     *用户，群头像
     * </pre>
     *
     * <code>USER_PORTRAIT = 1;</code>
     */
    USER_PORTRAIT(1),
    /**
     * <pre>
     * 个人消息，群图片消息
     * </pre>
     *
     * <code>MESSAGE_IMAGE = 2;</code>
     */
    MESSAGE_IMAGE(2),
    /**
     * <pre>
     * 个人，群语音消息
     * </pre>
     *
     * <code>MESSAGE_VOICE = 3;</code>
     */
    MESSAGE_VOICE(3),
    /**
     * <pre>
     *群头像
     * </pre>
     *
     * <code>GROUP_PORTRAIT = 4;</code>
     */
    GROUP_PORTRAIT(4),
    /**
     * <pre>
     * 站点扩展图片存放位置
     * </pre>
     *
     * <code>SITE_PLUGIN = 5;</code>
     */
    SITE_PLUGIN(5),
    /**
     * <pre>
     *站点本身相关图片，例如站点logo
     * </pre>
     *
     * <code>SITE_ICON = 6;</code>
     */
    SITE_ICON(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 未知的文件类型类型
     * </pre>
     *
     * <code>UNKNOWN_FILE = 0;</code>
     */
    public static final int UNKNOWN_FILE_VALUE = 0;
    /**
     * <pre>
     *用户，群头像
     * </pre>
     *
     * <code>USER_PORTRAIT = 1;</code>
     */
    public static final int USER_PORTRAIT_VALUE = 1;
    /**
     * <pre>
     * 个人消息，群图片消息
     * </pre>
     *
     * <code>MESSAGE_IMAGE = 2;</code>
     */
    public static final int MESSAGE_IMAGE_VALUE = 2;
    /**
     * <pre>
     * 个人，群语音消息
     * </pre>
     *
     * <code>MESSAGE_VOICE = 3;</code>
     */
    public static final int MESSAGE_VOICE_VALUE = 3;
    /**
     * <pre>
     *群头像
     * </pre>
     *
     * <code>GROUP_PORTRAIT = 4;</code>
     */
    public static final int GROUP_PORTRAIT_VALUE = 4;
    /**
     * <pre>
     * 站点扩展图片存放位置
     * </pre>
     *
     * <code>SITE_PLUGIN = 5;</code>
     */
    public static final int SITE_PLUGIN_VALUE = 5;
    /**
     * <pre>
     *站点本身相关图片，例如站点logo
     * </pre>
     *
     * <code>SITE_ICON = 6;</code>
     */
    public static final int SITE_ICON_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static FileType valueOf(int value) {
      return forNumber(value);
    }

    public static FileType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_FILE;
        case 1: return USER_PORTRAIT;
        case 2: return MESSAGE_IMAGE;
        case 3: return MESSAGE_VOICE;
        case 4: return GROUP_PORTRAIT;
        case 5: return SITE_PLUGIN;
        case 6: return SITE_ICON;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FileType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FileType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FileType>() {
            public FileType findValueByNumber(int number) {
              return FileType.forNumber(number);
            }
          };

    private final int value;

    private FileType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:core.FileType)
  }

  public interface FileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.File)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string file_id = 1;</code>
     */
    String getFileId();
    /**
     * <code>optional string file_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileIdBytes();

    /**
     * <code>optional bytes file_content = 2;</code>
     */
    com.google.protobuf.ByteString getFileContent();

    /**
     * <code>optional .core.FileType file_type = 3;</code>
     */
    int getFileTypeValue();
    /**
     * <code>optional .core.FileType file_type = 3;</code>
     */
    com.akaxin.proto.core.FileProto.FileType getFileType();
  }
  /**
   * <pre>
   *上传站点服务端的文件
   * </pre>
   *
   * Protobuf type {@code core.File}
   */
  public  static final class File extends
      com.google.protobuf.GeneratedMessageLite<
          File, File.Builder> implements
      // @@protoc_insertion_point(message_implements:core.File)
      FileOrBuilder {
    private File() {
      fileId_ = "";
      fileContent_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int FILE_ID_FIELD_NUMBER = 1;
    private String fileId_;
    /**
     * <code>optional string file_id = 1;</code>
     */
    public String getFileId() {
      return fileId_;
    }
    /**
     * <code>optional string file_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fileId_);
    }
    /**
     * <code>optional string file_id = 1;</code>
     */
    private void setFileId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      fileId_ = value;
    }
    /**
     * <code>optional string file_id = 1;</code>
     */
    private void clearFileId() {

      fileId_ = getDefaultInstance().getFileId();
    }
    /**
     * <code>optional string file_id = 1;</code>
     */
    private void setFileIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      fileId_ = value.toStringUtf8();
    }

    public static final int FILE_CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString fileContent_;
    /**
     * <code>optional bytes file_content = 2;</code>
     */
    public com.google.protobuf.ByteString getFileContent() {
      return fileContent_;
    }
    /**
     * <code>optional bytes file_content = 2;</code>
     */
    private void setFileContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      fileContent_ = value;
    }
    /**
     * <code>optional bytes file_content = 2;</code>
     */
    private void clearFileContent() {

      fileContent_ = getDefaultInstance().getFileContent();
    }

    public static final int FILE_TYPE_FIELD_NUMBER = 3;
    private int fileType_;
    /**
     * <code>optional .core.FileType file_type = 3;</code>
     */
    public int getFileTypeValue() {
      return fileType_;
    }
    /**
     * <code>optional .core.FileType file_type = 3;</code>
     */
    public com.akaxin.proto.core.FileProto.FileType getFileType() {
      com.akaxin.proto.core.FileProto.FileType result = com.akaxin.proto.core.FileProto.FileType.forNumber(fileType_);
      return result == null ? com.akaxin.proto.core.FileProto.FileType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .core.FileType file_type = 3;</code>
     */
    private void setFileTypeValue(int value) {
        fileType_ = value;
    }
    /**
     * <code>optional .core.FileType file_type = 3;</code>
     */
    private void setFileType(com.akaxin.proto.core.FileProto.FileType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      fileType_ = value.getNumber();
    }
    /**
     * <code>optional .core.FileType file_type = 3;</code>
     */
    private void clearFileType() {

      fileType_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!fileId_.isEmpty()) {
        output.writeString(1, getFileId());
      }
      if (!fileContent_.isEmpty()) {
        output.writeBytes(2, fileContent_);
      }
      if (fileType_ != com.akaxin.proto.core.FileProto.FileType.UNKNOWN_FILE.getNumber()) {
        output.writeEnum(3, fileType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!fileId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getFileId());
      }
      if (!fileContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, fileContent_);
      }
      if (fileType_ != com.akaxin.proto.core.FileProto.FileType.UNKNOWN_FILE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, fileType_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.akaxin.proto.core.FileProto.File parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.akaxin.proto.core.FileProto.File parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.akaxin.proto.core.FileProto.File parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.akaxin.proto.core.FileProto.File parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.akaxin.proto.core.FileProto.File parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.core.FileProto.File parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.akaxin.proto.core.FileProto.File parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.core.FileProto.File parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.akaxin.proto.core.FileProto.File parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.core.FileProto.File parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.core.FileProto.File prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *上传站点服务端的文件
     * </pre>
     *
     * Protobuf type {@code core.File}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          File, Builder> implements
        // @@protoc_insertion_point(builder_implements:core.File)
        com.akaxin.proto.core.FileProto.FileOrBuilder {
      // Construct using com.akaxin.proto.core.FileProto.File.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string file_id = 1;</code>
       */
      public String getFileId() {
        return instance.getFileId();
      }
      /**
       * <code>optional string file_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileIdBytes() {
        return instance.getFileIdBytes();
      }
      /**
       * <code>optional string file_id = 1;</code>
       */
      public Builder setFileId(
          String value) {
        copyOnWrite();
        instance.setFileId(value);
        return this;
      }
      /**
       * <code>optional string file_id = 1;</code>
       */
      public Builder clearFileId() {
        copyOnWrite();
        instance.clearFileId();
        return this;
      }
      /**
       * <code>optional string file_id = 1;</code>
       */
      public Builder setFileIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFileIdBytes(value);
        return this;
      }

      /**
       * <code>optional bytes file_content = 2;</code>
       */
      public com.google.protobuf.ByteString getFileContent() {
        return instance.getFileContent();
      }
      /**
       * <code>optional bytes file_content = 2;</code>
       */
      public Builder setFileContent(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFileContent(value);
        return this;
      }
      /**
       * <code>optional bytes file_content = 2;</code>
       */
      public Builder clearFileContent() {
        copyOnWrite();
        instance.clearFileContent();
        return this;
      }

      /**
       * <code>optional .core.FileType file_type = 3;</code>
       */
      public int getFileTypeValue() {
        return instance.getFileTypeValue();
      }
      /**
       * <code>optional .core.FileType file_type = 3;</code>
       */
      public Builder setFileTypeValue(int value) {
        copyOnWrite();
        instance.setFileTypeValue(value);
        return this;
      }
      /**
       * <code>optional .core.FileType file_type = 3;</code>
       */
      public com.akaxin.proto.core.FileProto.FileType getFileType() {
        return instance.getFileType();
      }
      /**
       * <code>optional .core.FileType file_type = 3;</code>
       */
      public Builder setFileType(com.akaxin.proto.core.FileProto.FileType value) {
        copyOnWrite();
        instance.setFileType(value);
        return this;
      }
      /**
       * <code>optional .core.FileType file_type = 3;</code>
       */
      public Builder clearFileType() {
        copyOnWrite();
        instance.clearFileType();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:core.File)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.akaxin.proto.core.FileProto.File();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.akaxin.proto.core.FileProto.File other = (com.akaxin.proto.core.FileProto.File) arg1;
          fileId_ = visitor.visitString(!fileId_.isEmpty(), fileId_,
              !other.fileId_.isEmpty(), other.fileId_);
          fileContent_ = visitor.visitByteString(fileContent_ != com.google.protobuf.ByteString.EMPTY, fileContent_,
              other.fileContent_ != com.google.protobuf.ByteString.EMPTY, other.fileContent_);
          fileType_ = visitor.visitInt(fileType_ != 0, fileType_,    other.fileType_ != 0, other.fileType_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  fileId_ = s;
                  break;
                }
                case 18: {

                  fileContent_ = input.readBytes();
                  break;
                }
                case 24: {
                  int rawValue = input.readEnum();

                  fileType_ = rawValue;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.akaxin.proto.core.FileProto.File.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:core.File)
    private static final com.akaxin.proto.core.FileProto.File DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new File();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.akaxin.proto.core.FileProto.File getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<File> PARSER;

    public static com.google.protobuf.Parser<File> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FileDescOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.FileDesc)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *语音的长度
     * </pre>
     *
     * <code>optional int32 length = 1;</code>
     */
    int getLength();

    /**
     * <pre>
     *图片的宽
     * </pre>
     *
     * <code>optional int32 width = 2;</code>
     */
    int getWidth();

    /**
     * <pre>
     *图片的高
     * </pre>
     *
     * <code>optional int32 height = 3;</code>
     */
    int getHeight();

    /**
     * <pre>
     *视频的大小，单位kb
     * </pre>
     *
     * <code>optional int32 size = 4;</code>
     */
    int getSize();
  }
  /**
   * <pre>
   * 文件信息的描述
   * </pre>
   *
   * Protobuf type {@code core.FileDesc}
   */
  public  static final class FileDesc extends
      com.google.protobuf.GeneratedMessageLite<
          FileDesc, FileDesc.Builder> implements
      // @@protoc_insertion_point(message_implements:core.FileDesc)
      FileDescOrBuilder {
    private FileDesc() {
    }
    public static final int LENGTH_FIELD_NUMBER = 1;
    private int length_;
    /**
     * <pre>
     *语音的长度
     * </pre>
     *
     * <code>optional int32 length = 1;</code>
     */
    public int getLength() {
      return length_;
    }
    /**
     * <pre>
     *语音的长度
     * </pre>
     *
     * <code>optional int32 length = 1;</code>
     */
    private void setLength(int value) {

      length_ = value;
    }
    /**
     * <pre>
     *语音的长度
     * </pre>
     *
     * <code>optional int32 length = 1;</code>
     */
    private void clearLength() {

      length_ = 0;
    }

    public static final int WIDTH_FIELD_NUMBER = 2;
    private int width_;
    /**
     * <pre>
     *图片的宽
     * </pre>
     *
     * <code>optional int32 width = 2;</code>
     */
    public int getWidth() {
      return width_;
    }
    /**
     * <pre>
     *图片的宽
     * </pre>
     *
     * <code>optional int32 width = 2;</code>
     */
    private void setWidth(int value) {

      width_ = value;
    }
    /**
     * <pre>
     *图片的宽
     * </pre>
     *
     * <code>optional int32 width = 2;</code>
     */
    private void clearWidth() {

      width_ = 0;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private int height_;
    /**
     * <pre>
     *图片的高
     * </pre>
     *
     * <code>optional int32 height = 3;</code>
     */
    public int getHeight() {
      return height_;
    }
    /**
     * <pre>
     *图片的高
     * </pre>
     *
     * <code>optional int32 height = 3;</code>
     */
    private void setHeight(int value) {

      height_ = value;
    }
    /**
     * <pre>
     *图片的高
     * </pre>
     *
     * <code>optional int32 height = 3;</code>
     */
    private void clearHeight() {

      height_ = 0;
    }

    public static final int SIZE_FIELD_NUMBER = 4;
    private int size_;
    /**
     * <pre>
     *视频的大小，单位kb
     * </pre>
     *
     * <code>optional int32 size = 4;</code>
     */
    public int getSize() {
      return size_;
    }
    /**
     * <pre>
     *视频的大小，单位kb
     * </pre>
     *
     * <code>optional int32 size = 4;</code>
     */
    private void setSize(int value) {

      size_ = value;
    }
    /**
     * <pre>
     *视频的大小，单位kb
     * </pre>
     *
     * <code>optional int32 size = 4;</code>
     */
    private void clearSize() {

      size_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (length_ != 0) {
        output.writeInt32(1, length_);
      }
      if (width_ != 0) {
        output.writeInt32(2, width_);
      }
      if (height_ != 0) {
        output.writeInt32(3, height_);
      }
      if (size_ != 0) {
        output.writeInt32(4, size_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (length_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, length_);
      }
      if (width_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, width_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, height_);
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, size_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.akaxin.proto.core.FileProto.FileDesc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.akaxin.proto.core.FileProto.FileDesc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.akaxin.proto.core.FileProto.FileDesc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.akaxin.proto.core.FileProto.FileDesc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.akaxin.proto.core.FileProto.FileDesc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.core.FileProto.FileDesc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.akaxin.proto.core.FileProto.FileDesc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.core.FileProto.FileDesc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.akaxin.proto.core.FileProto.FileDesc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.akaxin.proto.core.FileProto.FileDesc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.core.FileProto.FileDesc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 文件信息的描述
     * </pre>
     *
     * Protobuf type {@code core.FileDesc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          FileDesc, Builder> implements
        // @@protoc_insertion_point(builder_implements:core.FileDesc)
        com.akaxin.proto.core.FileProto.FileDescOrBuilder {
      // Construct using com.akaxin.proto.core.FileProto.FileDesc.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *语音的长度
       * </pre>
       *
       * <code>optional int32 length = 1;</code>
       */
      public int getLength() {
        return instance.getLength();
      }
      /**
       * <pre>
       *语音的长度
       * </pre>
       *
       * <code>optional int32 length = 1;</code>
       */
      public Builder setLength(int value) {
        copyOnWrite();
        instance.setLength(value);
        return this;
      }
      /**
       * <pre>
       *语音的长度
       * </pre>
       *
       * <code>optional int32 length = 1;</code>
       */
      public Builder clearLength() {
        copyOnWrite();
        instance.clearLength();
        return this;
      }

      /**
       * <pre>
       *图片的宽
       * </pre>
       *
       * <code>optional int32 width = 2;</code>
       */
      public int getWidth() {
        return instance.getWidth();
      }
      /**
       * <pre>
       *图片的宽
       * </pre>
       *
       * <code>optional int32 width = 2;</code>
       */
      public Builder setWidth(int value) {
        copyOnWrite();
        instance.setWidth(value);
        return this;
      }
      /**
       * <pre>
       *图片的宽
       * </pre>
       *
       * <code>optional int32 width = 2;</code>
       */
      public Builder clearWidth() {
        copyOnWrite();
        instance.clearWidth();
        return this;
      }

      /**
       * <pre>
       *图片的高
       * </pre>
       *
       * <code>optional int32 height = 3;</code>
       */
      public int getHeight() {
        return instance.getHeight();
      }
      /**
       * <pre>
       *图片的高
       * </pre>
       *
       * <code>optional int32 height = 3;</code>
       */
      public Builder setHeight(int value) {
        copyOnWrite();
        instance.setHeight(value);
        return this;
      }
      /**
       * <pre>
       *图片的高
       * </pre>
       *
       * <code>optional int32 height = 3;</code>
       */
      public Builder clearHeight() {
        copyOnWrite();
        instance.clearHeight();
        return this;
      }

      /**
       * <pre>
       *视频的大小，单位kb
       * </pre>
       *
       * <code>optional int32 size = 4;</code>
       */
      public int getSize() {
        return instance.getSize();
      }
      /**
       * <pre>
       *视频的大小，单位kb
       * </pre>
       *
       * <code>optional int32 size = 4;</code>
       */
      public Builder setSize(int value) {
        copyOnWrite();
        instance.setSize(value);
        return this;
      }
      /**
       * <pre>
       *视频的大小，单位kb
       * </pre>
       *
       * <code>optional int32 size = 4;</code>
       */
      public Builder clearSize() {
        copyOnWrite();
        instance.clearSize();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:core.FileDesc)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.akaxin.proto.core.FileProto.FileDesc();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.akaxin.proto.core.FileProto.FileDesc other = (com.akaxin.proto.core.FileProto.FileDesc) arg1;
          length_ = visitor.visitInt(length_ != 0, length_,
              other.length_ != 0, other.length_);
          width_ = visitor.visitInt(width_ != 0, width_,
              other.width_ != 0, other.width_);
          height_ = visitor.visitInt(height_ != 0, height_,
              other.height_ != 0, other.height_);
          size_ = visitor.visitInt(size_ != 0, size_,
              other.size_ != 0, other.size_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  length_ = input.readInt32();
                  break;
                }
                case 16: {

                  width_ = input.readInt32();
                  break;
                }
                case 24: {

                  height_ = input.readInt32();
                  break;
                }
                case 32: {

                  size_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.akaxin.proto.core.FileProto.FileDesc.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:core.FileDesc)
    private static final com.akaxin.proto.core.FileProto.FileDesc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FileDesc();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.akaxin.proto.core.FileProto.FileDesc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FileDesc> PARSER;

    public static com.google.protobuf.Parser<FileDesc> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
