// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/api_phone_login.proto

package com.windchat.proto.platform;

public final class ApiPhoneLoginProto {
  private ApiPhoneLoginProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ApiPhoneLoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiPhoneLoginRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *用户手机号码
     * </pre>
     *
     * <code>optional string phone_id = 1;</code>
     */
    String getPhoneId();
    /**
     * <pre>
     *用户手机号码
     * </pre>
     *
     * <code>optional string phone_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getPhoneIdBytes();

    /**
     * <pre>
     *短信验证码
     * </pre>
     *
     * <code>optional string phone_verify_code = 2;</code>
     */
    String getPhoneVerifyCode();
    /**
     * <pre>
     *短信验证码
     * </pre>
     *
     * <code>optional string phone_verify_code = 2;</code>
     */
    com.google.protobuf.ByteString
        getPhoneVerifyCodeBytes();

    /**
     * <pre>
     *手机验证码类型,vc_type=1
     * </pre>
     *
     * <code>optional int32 vc_type = 3;</code>
     */
    int getVcType();

    /**
     * <pre>
     *+86
     * </pre>
     *
     * <code>optional string country_code = 4;</code>
     */
    String getCountryCode();
    /**
     * <pre>
     *+86
     * </pre>
     *
     * <code>optional string country_code = 4;</code>
     */
    com.google.protobuf.ByteString
        getCountryCodeBytes();
  }
  /**
   * Protobuf type {@code platform.ApiPhoneLoginRequest}
   */
  public  static final class ApiPhoneLoginRequest extends
      com.google.protobuf.GeneratedMessageLite<
          ApiPhoneLoginRequest, ApiPhoneLoginRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:platform.ApiPhoneLoginRequest)
      ApiPhoneLoginRequestOrBuilder {
    private ApiPhoneLoginRequest() {
      phoneId_ = "";
      phoneVerifyCode_ = "";
      countryCode_ = "";
    }
    public static final int PHONE_ID_FIELD_NUMBER = 1;
    private String phoneId_;
    /**
     * <pre>
     *用户手机号码
     * </pre>
     *
     * <code>optional string phone_id = 1;</code>
     */
    public String getPhoneId() {
      return phoneId_;
    }
    /**
     * <pre>
     *用户手机号码
     * </pre>
     *
     * <code>optional string phone_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(phoneId_);
    }
    /**
     * <pre>
     *用户手机号码
     * </pre>
     *
     * <code>optional string phone_id = 1;</code>
     */
    private void setPhoneId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      phoneId_ = value;
    }
    /**
     * <pre>
     *用户手机号码
     * </pre>
     *
     * <code>optional string phone_id = 1;</code>
     */
    private void clearPhoneId() {

      phoneId_ = getDefaultInstance().getPhoneId();
    }
    /**
     * <pre>
     *用户手机号码
     * </pre>
     *
     * <code>optional string phone_id = 1;</code>
     */
    private void setPhoneIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      phoneId_ = value.toStringUtf8();
    }

    public static final int PHONE_VERIFY_CODE_FIELD_NUMBER = 2;
    private String phoneVerifyCode_;
    /**
     * <pre>
     *短信验证码
     * </pre>
     *
     * <code>optional string phone_verify_code = 2;</code>
     */
    public String getPhoneVerifyCode() {
      return phoneVerifyCode_;
    }
    /**
     * <pre>
     *短信验证码
     * </pre>
     *
     * <code>optional string phone_verify_code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneVerifyCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(phoneVerifyCode_);
    }
    /**
     * <pre>
     *短信验证码
     * </pre>
     *
     * <code>optional string phone_verify_code = 2;</code>
     */
    private void setPhoneVerifyCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      phoneVerifyCode_ = value;
    }
    /**
     * <pre>
     *短信验证码
     * </pre>
     *
     * <code>optional string phone_verify_code = 2;</code>
     */
    private void clearPhoneVerifyCode() {

      phoneVerifyCode_ = getDefaultInstance().getPhoneVerifyCode();
    }
    /**
     * <pre>
     *短信验证码
     * </pre>
     *
     * <code>optional string phone_verify_code = 2;</code>
     */
    private void setPhoneVerifyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      phoneVerifyCode_ = value.toStringUtf8();
    }

    public static final int VC_TYPE_FIELD_NUMBER = 3;
    private int vcType_;
    /**
     * <pre>
     *手机验证码类型,vc_type=1
     * </pre>
     *
     * <code>optional int32 vc_type = 3;</code>
     */
    public int getVcType() {
      return vcType_;
    }
    /**
     * <pre>
     *手机验证码类型,vc_type=1
     * </pre>
     *
     * <code>optional int32 vc_type = 3;</code>
     */
    private void setVcType(int value) {

      vcType_ = value;
    }
    /**
     * <pre>
     *手机验证码类型,vc_type=1
     * </pre>
     *
     * <code>optional int32 vc_type = 3;</code>
     */
    private void clearVcType() {

      vcType_ = 0;
    }

    public static final int COUNTRY_CODE_FIELD_NUMBER = 4;
    private String countryCode_;
    /**
     * <pre>
     *+86
     * </pre>
     *
     * <code>optional string country_code = 4;</code>
     */
    public String getCountryCode() {
      return countryCode_;
    }
    /**
     * <pre>
     *+86
     * </pre>
     *
     * <code>optional string country_code = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(countryCode_);
    }
    /**
     * <pre>
     *+86
     * </pre>
     *
     * <code>optional string country_code = 4;</code>
     */
    private void setCountryCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      countryCode_ = value;
    }
    /**
     * <pre>
     *+86
     * </pre>
     *
     * <code>optional string country_code = 4;</code>
     */
    private void clearCountryCode() {

      countryCode_ = getDefaultInstance().getCountryCode();
    }
    /**
     * <pre>
     *+86
     * </pre>
     *
     * <code>optional string country_code = 4;</code>
     */
    private void setCountryCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      countryCode_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!phoneId_.isEmpty()) {
        output.writeString(1, getPhoneId());
      }
      if (!phoneVerifyCode_.isEmpty()) {
        output.writeString(2, getPhoneVerifyCode());
      }
      if (vcType_ != 0) {
        output.writeInt32(3, vcType_);
      }
      if (!countryCode_.isEmpty()) {
        output.writeString(4, getCountryCode());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!phoneId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getPhoneId());
      }
      if (!phoneVerifyCode_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPhoneVerifyCode());
      }
      if (vcType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, vcType_);
      }
      if (!countryCode_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getCountryCode());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ApiPhoneLoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiPhoneLoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiPhoneLoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiPhoneLoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiPhoneLoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiPhoneLoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiPhoneLoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApiPhoneLoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiPhoneLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiPhoneLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApiPhoneLoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code platform.ApiPhoneLoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApiPhoneLoginRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiPhoneLoginRequest)
        ApiPhoneLoginRequestOrBuilder {
      // Construct using com.windchat.proto.platform.ApiPhoneLoginProto.ApiPhoneLoginRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *用户手机号码
       * </pre>
       *
       * <code>optional string phone_id = 1;</code>
       */
      public String getPhoneId() {
        return instance.getPhoneId();
      }
      /**
       * <pre>
       *用户手机号码
       * </pre>
       *
       * <code>optional string phone_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneIdBytes() {
        return instance.getPhoneIdBytes();
      }
      /**
       * <pre>
       *用户手机号码
       * </pre>
       *
       * <code>optional string phone_id = 1;</code>
       */
      public Builder setPhoneId(
          String value) {
        copyOnWrite();
        instance.setPhoneId(value);
        return this;
      }
      /**
       * <pre>
       *用户手机号码
       * </pre>
       *
       * <code>optional string phone_id = 1;</code>
       */
      public Builder clearPhoneId() {
        copyOnWrite();
        instance.clearPhoneId();
        return this;
      }
      /**
       * <pre>
       *用户手机号码
       * </pre>
       *
       * <code>optional string phone_id = 1;</code>
       */
      public Builder setPhoneIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPhoneIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *短信验证码
       * </pre>
       *
       * <code>optional string phone_verify_code = 2;</code>
       */
      public String getPhoneVerifyCode() {
        return instance.getPhoneVerifyCode();
      }
      /**
       * <pre>
       *短信验证码
       * </pre>
       *
       * <code>optional string phone_verify_code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneVerifyCodeBytes() {
        return instance.getPhoneVerifyCodeBytes();
      }
      /**
       * <pre>
       *短信验证码
       * </pre>
       *
       * <code>optional string phone_verify_code = 2;</code>
       */
      public Builder setPhoneVerifyCode(
          String value) {
        copyOnWrite();
        instance.setPhoneVerifyCode(value);
        return this;
      }
      /**
       * <pre>
       *短信验证码
       * </pre>
       *
       * <code>optional string phone_verify_code = 2;</code>
       */
      public Builder clearPhoneVerifyCode() {
        copyOnWrite();
        instance.clearPhoneVerifyCode();
        return this;
      }
      /**
       * <pre>
       *短信验证码
       * </pre>
       *
       * <code>optional string phone_verify_code = 2;</code>
       */
      public Builder setPhoneVerifyCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPhoneVerifyCodeBytes(value);
        return this;
      }

      /**
       * <pre>
       *手机验证码类型,vc_type=1
       * </pre>
       *
       * <code>optional int32 vc_type = 3;</code>
       */
      public int getVcType() {
        return instance.getVcType();
      }
      /**
       * <pre>
       *手机验证码类型,vc_type=1
       * </pre>
       *
       * <code>optional int32 vc_type = 3;</code>
       */
      public Builder setVcType(int value) {
        copyOnWrite();
        instance.setVcType(value);
        return this;
      }
      /**
       * <pre>
       *手机验证码类型,vc_type=1
       * </pre>
       *
       * <code>optional int32 vc_type = 3;</code>
       */
      public Builder clearVcType() {
        copyOnWrite();
        instance.clearVcType();
        return this;
      }

      /**
       * <pre>
       *+86
       * </pre>
       *
       * <code>optional string country_code = 4;</code>
       */
      public String getCountryCode() {
        return instance.getCountryCode();
      }
      /**
       * <pre>
       *+86
       * </pre>
       *
       * <code>optional string country_code = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCountryCodeBytes() {
        return instance.getCountryCodeBytes();
      }
      /**
       * <pre>
       *+86
       * </pre>
       *
       * <code>optional string country_code = 4;</code>
       */
      public Builder setCountryCode(
          String value) {
        copyOnWrite();
        instance.setCountryCode(value);
        return this;
      }
      /**
       * <pre>
       *+86
       * </pre>
       *
       * <code>optional string country_code = 4;</code>
       */
      public Builder clearCountryCode() {
        copyOnWrite();
        instance.clearCountryCode();
        return this;
      }
      /**
       * <pre>
       *+86
       * </pre>
       *
       * <code>optional string country_code = 4;</code>
       */
      public Builder setCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCountryCodeBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:platform.ApiPhoneLoginRequest)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApiPhoneLoginRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApiPhoneLoginRequest other = (ApiPhoneLoginRequest) arg1;
          phoneId_ = visitor.visitString(!phoneId_.isEmpty(), phoneId_,
              !other.phoneId_.isEmpty(), other.phoneId_);
          phoneVerifyCode_ = visitor.visitString(!phoneVerifyCode_.isEmpty(), phoneVerifyCode_,
              !other.phoneVerifyCode_.isEmpty(), other.phoneVerifyCode_);
          vcType_ = visitor.visitInt(vcType_ != 0, vcType_,
              other.vcType_ != 0, other.vcType_);
          countryCode_ = visitor.visitString(!countryCode_.isEmpty(), countryCode_,
              !other.countryCode_.isEmpty(), other.countryCode_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  phoneId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  phoneVerifyCode_ = s;
                  break;
                }
                case 24: {

                  vcType_ = input.readInt32();
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  countryCode_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApiPhoneLoginRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:platform.ApiPhoneLoginRequest)
    private static final ApiPhoneLoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApiPhoneLoginRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApiPhoneLoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApiPhoneLoginRequest> PARSER;

    public static com.google.protobuf.Parser<ApiPhoneLoginRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ApiPhoneLoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiPhoneLoginResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    String getUserIdPrik();
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPrikBytes();

    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    String getUserIdPubk();
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPubkBytes();
  }
  /**
   * Protobuf type {@code platform.ApiPhoneLoginResponse}
   */
  public  static final class ApiPhoneLoginResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ApiPhoneLoginResponse, ApiPhoneLoginResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:platform.ApiPhoneLoginResponse)
      ApiPhoneLoginResponseOrBuilder {
    private ApiPhoneLoginResponse() {
      userIdPrik_ = "";
      userIdPubk_ = "";
    }
    public static final int USER_ID_PRIK_FIELD_NUMBER = 1;
    private String userIdPrik_;
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    public String getUserIdPrik() {
      return userIdPrik_;
    }
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPrikBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userIdPrik_);
    }
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    private void setUserIdPrik(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      userIdPrik_ = value;
    }
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    private void clearUserIdPrik() {

      userIdPrik_ = getDefaultInstance().getUserIdPrik();
    }
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    private void setUserIdPrikBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      userIdPrik_ = value.toStringUtf8();
    }

    public static final int USER_ID_PUBK_FIELD_NUMBER = 2;
    private String userIdPubk_;
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    public String getUserIdPubk() {
      return userIdPubk_;
    }
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPubkBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userIdPubk_);
    }
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    private void setUserIdPubk(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      userIdPubk_ = value;
    }
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    private void clearUserIdPubk() {

      userIdPubk_ = getDefaultInstance().getUserIdPubk();
    }
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    private void setUserIdPubkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      userIdPubk_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!userIdPrik_.isEmpty()) {
        output.writeString(1, getUserIdPrik());
      }
      if (!userIdPubk_.isEmpty()) {
        output.writeString(2, getUserIdPubk());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!userIdPrik_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUserIdPrik());
      }
      if (!userIdPubk_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getUserIdPubk());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ApiPhoneLoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiPhoneLoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiPhoneLoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiPhoneLoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiPhoneLoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiPhoneLoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiPhoneLoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApiPhoneLoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiPhoneLoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiPhoneLoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApiPhoneLoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code platform.ApiPhoneLoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApiPhoneLoginResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiPhoneLoginResponse)
        ApiPhoneLoginResponseOrBuilder {
      // Construct using com.windchat.proto.platform.ApiPhoneLoginProto.ApiPhoneLoginResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public String getUserIdPrik() {
        return instance.getUserIdPrik();
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPrikBytes() {
        return instance.getUserIdPrikBytes();
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public Builder setUserIdPrik(
          String value) {
        copyOnWrite();
        instance.setUserIdPrik(value);
        return this;
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public Builder clearUserIdPrik() {
        copyOnWrite();
        instance.clearUserIdPrik();
        return this;
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public Builder setUserIdPrikBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdPrikBytes(value);
        return this;
      }

      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public String getUserIdPubk() {
        return instance.getUserIdPubk();
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPubkBytes() {
        return instance.getUserIdPubkBytes();
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public Builder setUserIdPubk(
          String value) {
        copyOnWrite();
        instance.setUserIdPubk(value);
        return this;
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public Builder clearUserIdPubk() {
        copyOnWrite();
        instance.clearUserIdPubk();
        return this;
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public Builder setUserIdPubkBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdPubkBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:platform.ApiPhoneLoginResponse)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApiPhoneLoginResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApiPhoneLoginResponse other = (ApiPhoneLoginResponse) arg1;
          userIdPrik_ = visitor.visitString(!userIdPrik_.isEmpty(), userIdPrik_,
              !other.userIdPrik_.isEmpty(), other.userIdPrik_);
          userIdPubk_ = visitor.visitString(!userIdPubk_.isEmpty(), userIdPubk_,
              !other.userIdPubk_.isEmpty(), other.userIdPubk_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  userIdPrik_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  userIdPubk_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApiPhoneLoginResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:platform.ApiPhoneLoginResponse)
    private static final ApiPhoneLoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApiPhoneLoginResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApiPhoneLoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApiPhoneLoginResponse> PARSER;

    public static com.google.protobuf.Parser<ApiPhoneLoginResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
