// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/api_friend_updateMute.proto

package com.windchat.proto.server;

public final class ApiFriendUpdateMuteProto {
  private ApiFriendUpdateMuteProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ApiFriendUpdateMuteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiFriendUpdateMuteRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *好友用户ID
     * </pre>
     *
     * <code>optional string site_friend_id = 1;</code>
     */
    String getSiteFriendId();
    /**
     * <pre>
     *好友用户ID
     * </pre>
     *
     * <code>optional string site_friend_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSiteFriendIdBytes();

    /**
     * <pre>
     *消息免打扰状态
     * </pre>
     *
     * <code>optional bool mute = 2;</code>
     */
    boolean getMute();
  }
  /**
   * Protobuf type {@code site.ApiFriendUpdateMuteRequest}
   */
  public  static final class ApiFriendUpdateMuteRequest extends
      com.google.protobuf.GeneratedMessageLite<
          ApiFriendUpdateMuteRequest, ApiFriendUpdateMuteRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:site.ApiFriendUpdateMuteRequest)
      ApiFriendUpdateMuteRequestOrBuilder {
    private ApiFriendUpdateMuteRequest() {
      siteFriendId_ = "";
    }
    public static final int SITE_FRIEND_ID_FIELD_NUMBER = 1;
    private String siteFriendId_;
    /**
     * <pre>
     *好友用户ID
     * </pre>
     *
     * <code>optional string site_friend_id = 1;</code>
     */
    public String getSiteFriendId() {
      return siteFriendId_;
    }
    /**
     * <pre>
     *好友用户ID
     * </pre>
     *
     * <code>optional string site_friend_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSiteFriendIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(siteFriendId_);
    }
    /**
     * <pre>
     *好友用户ID
     * </pre>
     *
     * <code>optional string site_friend_id = 1;</code>
     */
    private void setSiteFriendId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      siteFriendId_ = value;
    }
    /**
     * <pre>
     *好友用户ID
     * </pre>
     *
     * <code>optional string site_friend_id = 1;</code>
     */
    private void clearSiteFriendId() {

      siteFriendId_ = getDefaultInstance().getSiteFriendId();
    }
    /**
     * <pre>
     *好友用户ID
     * </pre>
     *
     * <code>optional string site_friend_id = 1;</code>
     */
    private void setSiteFriendIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      siteFriendId_ = value.toStringUtf8();
    }

    public static final int MUTE_FIELD_NUMBER = 2;
    private boolean mute_;
    /**
     * <pre>
     *消息免打扰状态
     * </pre>
     *
     * <code>optional bool mute = 2;</code>
     */
    public boolean getMute() {
      return mute_;
    }
    /**
     * <pre>
     *消息免打扰状态
     * </pre>
     *
     * <code>optional bool mute = 2;</code>
     */
    private void setMute(boolean value) {

      mute_ = value;
    }
    /**
     * <pre>
     *消息免打扰状态
     * </pre>
     *
     * <code>optional bool mute = 2;</code>
     */
    private void clearMute() {

      mute_ = false;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!siteFriendId_.isEmpty()) {
        output.writeString(1, getSiteFriendId());
      }
      if (mute_ != false) {
        output.writeBool(2, mute_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!siteFriendId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSiteFriendId());
      }
      if (mute_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, mute_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ApiFriendUpdateMuteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiFriendUpdateMuteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiFriendUpdateMuteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiFriendUpdateMuteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiFriendUpdateMuteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiFriendUpdateMuteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiFriendUpdateMuteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApiFriendUpdateMuteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiFriendUpdateMuteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiFriendUpdateMuteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApiFriendUpdateMuteRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code site.ApiFriendUpdateMuteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApiFriendUpdateMuteRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiFriendUpdateMuteRequest)
        ApiFriendUpdateMuteRequestOrBuilder {
      // Construct using com.windchat.proto.server.ApiFriendUpdateMuteProto.ApiFriendUpdateMuteRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *好友用户ID
       * </pre>
       *
       * <code>optional string site_friend_id = 1;</code>
       */
      public String getSiteFriendId() {
        return instance.getSiteFriendId();
      }
      /**
       * <pre>
       *好友用户ID
       * </pre>
       *
       * <code>optional string site_friend_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSiteFriendIdBytes() {
        return instance.getSiteFriendIdBytes();
      }
      /**
       * <pre>
       *好友用户ID
       * </pre>
       *
       * <code>optional string site_friend_id = 1;</code>
       */
      public Builder setSiteFriendId(
          String value) {
        copyOnWrite();
        instance.setSiteFriendId(value);
        return this;
      }
      /**
       * <pre>
       *好友用户ID
       * </pre>
       *
       * <code>optional string site_friend_id = 1;</code>
       */
      public Builder clearSiteFriendId() {
        copyOnWrite();
        instance.clearSiteFriendId();
        return this;
      }
      /**
       * <pre>
       *好友用户ID
       * </pre>
       *
       * <code>optional string site_friend_id = 1;</code>
       */
      public Builder setSiteFriendIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSiteFriendIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *消息免打扰状态
       * </pre>
       *
       * <code>optional bool mute = 2;</code>
       */
      public boolean getMute() {
        return instance.getMute();
      }
      /**
       * <pre>
       *消息免打扰状态
       * </pre>
       *
       * <code>optional bool mute = 2;</code>
       */
      public Builder setMute(boolean value) {
        copyOnWrite();
        instance.setMute(value);
        return this;
      }
      /**
       * <pre>
       *消息免打扰状态
       * </pre>
       *
       * <code>optional bool mute = 2;</code>
       */
      public Builder clearMute() {
        copyOnWrite();
        instance.clearMute();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:site.ApiFriendUpdateMuteRequest)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApiFriendUpdateMuteRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApiFriendUpdateMuteRequest other = (ApiFriendUpdateMuteRequest) arg1;
          siteFriendId_ = visitor.visitString(!siteFriendId_.isEmpty(), siteFriendId_,
              !other.siteFriendId_.isEmpty(), other.siteFriendId_);
          mute_ = visitor.visitBoolean(mute_ != false, mute_,
              other.mute_ != false, other.mute_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  siteFriendId_ = s;
                  break;
                }
                case 16: {

                  mute_ = input.readBool();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApiFriendUpdateMuteRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:site.ApiFriendUpdateMuteRequest)
    private static final ApiFriendUpdateMuteRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApiFriendUpdateMuteRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApiFriendUpdateMuteRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApiFriendUpdateMuteRequest> PARSER;

    public static com.google.protobuf.Parser<ApiFriendUpdateMuteRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ApiFriendUpdateMuteResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiFriendUpdateMuteResponse)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code site.ApiFriendUpdateMuteResponse}
   */
  public  static final class ApiFriendUpdateMuteResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ApiFriendUpdateMuteResponse, ApiFriendUpdateMuteResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:site.ApiFriendUpdateMuteResponse)
      ApiFriendUpdateMuteResponseOrBuilder {
    private ApiFriendUpdateMuteResponse() {
    }
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    public static ApiFriendUpdateMuteResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiFriendUpdateMuteResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiFriendUpdateMuteResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiFriendUpdateMuteResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiFriendUpdateMuteResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiFriendUpdateMuteResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiFriendUpdateMuteResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApiFriendUpdateMuteResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiFriendUpdateMuteResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiFriendUpdateMuteResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApiFriendUpdateMuteResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code site.ApiFriendUpdateMuteResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApiFriendUpdateMuteResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiFriendUpdateMuteResponse)
        ApiFriendUpdateMuteResponseOrBuilder {
      // Construct using com.windchat.proto.server.ApiFriendUpdateMuteProto.ApiFriendUpdateMuteResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:site.ApiFriendUpdateMuteResponse)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApiFriendUpdateMuteResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApiFriendUpdateMuteResponse other = (ApiFriendUpdateMuteResponse) arg1;
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApiFriendUpdateMuteResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:site.ApiFriendUpdateMuteResponse)
    private static final ApiFriendUpdateMuteResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApiFriendUpdateMuteResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApiFriendUpdateMuteResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApiFriendUpdateMuteResponse> PARSER;

    public static com.google.protobuf.Parser<ApiFriendUpdateMuteResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
