// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/api_group_updateProfile.proto

package com.windchat.proto.server;

public final class ApiGroupUpdateProfileProto {
  private ApiGroupUpdateProfileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ApiGroupUpdateProfileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiGroupUpdateProfileRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *需要更新的群组资料
     * </pre>
     *
     * <code>optional .core.GroupProfile profile = 1;</code>
     */
    boolean hasProfile();
    /**
     * <pre>
     *需要更新的群组资料
     * </pre>
     *
     * <code>optional .core.GroupProfile profile = 1;</code>
     */
    com.windchat.proto.core.GroupProto.GroupProfile getProfile();

    /**
     * <pre>
     *新的群主
     * </pre>
     *
     * <code>optional string new_group_owner = 2;</code>
     */
    String getNewGroupOwner();
    /**
     * <pre>
     *新的群主
     * </pre>
     *
     * <code>optional string new_group_owner = 2;</code>
     */
    com.google.protobuf.ByteString
        getNewGroupOwnerBytes();

    /**
     * <pre>
     *是否关闭群聊邀请 true：打开 false：关闭
     * </pre>
     *
     * <code>optional bool close_invite_group_chat = 3;</code>
     */
    boolean getCloseInviteGroupChat();
  }
  /**
   * Protobuf type {@code site.ApiGroupUpdateProfileRequest}
   */
  public  static final class ApiGroupUpdateProfileRequest extends
      com.google.protobuf.GeneratedMessageLite<
          ApiGroupUpdateProfileRequest, ApiGroupUpdateProfileRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:site.ApiGroupUpdateProfileRequest)
      ApiGroupUpdateProfileRequestOrBuilder {
    private ApiGroupUpdateProfileRequest() {
      newGroupOwner_ = "";
    }
    public static final int PROFILE_FIELD_NUMBER = 1;
    private com.windchat.proto.core.GroupProto.GroupProfile profile_;
    /**
     * <pre>
     *需要更新的群组资料
     * </pre>
     *
     * <code>optional .core.GroupProfile profile = 1;</code>
     */
    public boolean hasProfile() {
      return profile_ != null;
    }
    /**
     * <pre>
     *需要更新的群组资料
     * </pre>
     *
     * <code>optional .core.GroupProfile profile = 1;</code>
     */
    public com.windchat.proto.core.GroupProto.GroupProfile getProfile() {
      return profile_ == null ? com.windchat.proto.core.GroupProto.GroupProfile.getDefaultInstance() : profile_;
    }
    /**
     * <pre>
     *需要更新的群组资料
     * </pre>
     *
     * <code>optional .core.GroupProfile profile = 1;</code>
     */
    private void setProfile(com.windchat.proto.core.GroupProto.GroupProfile value) {
      if (value == null) {
        throw new NullPointerException();
      }
      profile_ = value;

      }
    /**
     * <pre>
     *需要更新的群组资料
     * </pre>
     *
     * <code>optional .core.GroupProfile profile = 1;</code>
     */
    private void setProfile(
        com.windchat.proto.core.GroupProto.GroupProfile.Builder builderForValue) {
      profile_ = builderForValue.build();

    }
    /**
     * <pre>
     *需要更新的群组资料
     * </pre>
     *
     * <code>optional .core.GroupProfile profile = 1;</code>
     */
    private void mergeProfile(com.windchat.proto.core.GroupProto.GroupProfile value) {
      if (profile_ != null &&
          profile_ != com.windchat.proto.core.GroupProto.GroupProfile.getDefaultInstance()) {
        profile_ =
          com.windchat.proto.core.GroupProto.GroupProfile.newBuilder(profile_).mergeFrom(value).buildPartial();
      } else {
        profile_ = value;
      }

    }
    /**
     * <pre>
     *需要更新的群组资料
     * </pre>
     *
     * <code>optional .core.GroupProfile profile = 1;</code>
     */
    private void clearProfile() {  profile_ = null;

    }

    public static final int NEW_GROUP_OWNER_FIELD_NUMBER = 2;
    private String newGroupOwner_;
    /**
     * <pre>
     *新的群主
     * </pre>
     *
     * <code>optional string new_group_owner = 2;</code>
     */
    public String getNewGroupOwner() {
      return newGroupOwner_;
    }
    /**
     * <pre>
     *新的群主
     * </pre>
     *
     * <code>optional string new_group_owner = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNewGroupOwnerBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(newGroupOwner_);
    }
    /**
     * <pre>
     *新的群主
     * </pre>
     *
     * <code>optional string new_group_owner = 2;</code>
     */
    private void setNewGroupOwner(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      newGroupOwner_ = value;
    }
    /**
     * <pre>
     *新的群主
     * </pre>
     *
     * <code>optional string new_group_owner = 2;</code>
     */
    private void clearNewGroupOwner() {

      newGroupOwner_ = getDefaultInstance().getNewGroupOwner();
    }
    /**
     * <pre>
     *新的群主
     * </pre>
     *
     * <code>optional string new_group_owner = 2;</code>
     */
    private void setNewGroupOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      newGroupOwner_ = value.toStringUtf8();
    }

    public static final int CLOSE_INVITE_GROUP_CHAT_FIELD_NUMBER = 3;
    private boolean closeInviteGroupChat_;
    /**
     * <pre>
     *是否关闭群聊邀请 true：打开 false：关闭
     * </pre>
     *
     * <code>optional bool close_invite_group_chat = 3;</code>
     */
    public boolean getCloseInviteGroupChat() {
      return closeInviteGroupChat_;
    }
    /**
     * <pre>
     *是否关闭群聊邀请 true：打开 false：关闭
     * </pre>
     *
     * <code>optional bool close_invite_group_chat = 3;</code>
     */
    private void setCloseInviteGroupChat(boolean value) {

      closeInviteGroupChat_ = value;
    }
    /**
     * <pre>
     *是否关闭群聊邀请 true：打开 false：关闭
     * </pre>
     *
     * <code>optional bool close_invite_group_chat = 3;</code>
     */
    private void clearCloseInviteGroupChat() {

      closeInviteGroupChat_ = false;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (profile_ != null) {
        output.writeMessage(1, getProfile());
      }
      if (!newGroupOwner_.isEmpty()) {
        output.writeString(2, getNewGroupOwner());
      }
      if (closeInviteGroupChat_ != false) {
        output.writeBool(3, closeInviteGroupChat_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (profile_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getProfile());
      }
      if (!newGroupOwner_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNewGroupOwner());
      }
      if (closeInviteGroupChat_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, closeInviteGroupChat_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ApiGroupUpdateProfileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiGroupUpdateProfileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiGroupUpdateProfileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiGroupUpdateProfileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiGroupUpdateProfileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiGroupUpdateProfileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiGroupUpdateProfileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApiGroupUpdateProfileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiGroupUpdateProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiGroupUpdateProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApiGroupUpdateProfileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code site.ApiGroupUpdateProfileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApiGroupUpdateProfileRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiGroupUpdateProfileRequest)
        ApiGroupUpdateProfileRequestOrBuilder {
      // Construct using com.windchat.proto.server.ApiGroupUpdateProfileProto.ApiGroupUpdateProfileRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *需要更新的群组资料
       * </pre>
       *
       * <code>optional .core.GroupProfile profile = 1;</code>
       */
      public boolean hasProfile() {
        return instance.hasProfile();
      }
      /**
       * <pre>
       *需要更新的群组资料
       * </pre>
       *
       * <code>optional .core.GroupProfile profile = 1;</code>
       */
      public com.windchat.proto.core.GroupProto.GroupProfile getProfile() {
        return instance.getProfile();
      }
      /**
       * <pre>
       *需要更新的群组资料
       * </pre>
       *
       * <code>optional .core.GroupProfile profile = 1;</code>
       */
      public Builder setProfile(com.windchat.proto.core.GroupProto.GroupProfile value) {
        copyOnWrite();
        instance.setProfile(value);
        return this;
        }
      /**
       * <pre>
       *需要更新的群组资料
       * </pre>
       *
       * <code>optional .core.GroupProfile profile = 1;</code>
       */
      public Builder setProfile(
          com.windchat.proto.core.GroupProto.GroupProfile.Builder builderForValue) {
        copyOnWrite();
        instance.setProfile(builderForValue);
        return this;
      }
      /**
       * <pre>
       *需要更新的群组资料
       * </pre>
       *
       * <code>optional .core.GroupProfile profile = 1;</code>
       */
      public Builder mergeProfile(com.windchat.proto.core.GroupProto.GroupProfile value) {
        copyOnWrite();
        instance.mergeProfile(value);
        return this;
      }
      /**
       * <pre>
       *需要更新的群组资料
       * </pre>
       *
       * <code>optional .core.GroupProfile profile = 1;</code>
       */
      public Builder clearProfile() {  copyOnWrite();
        instance.clearProfile();
        return this;
      }

      /**
       * <pre>
       *新的群主
       * </pre>
       *
       * <code>optional string new_group_owner = 2;</code>
       */
      public String getNewGroupOwner() {
        return instance.getNewGroupOwner();
      }
      /**
       * <pre>
       *新的群主
       * </pre>
       *
       * <code>optional string new_group_owner = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNewGroupOwnerBytes() {
        return instance.getNewGroupOwnerBytes();
      }
      /**
       * <pre>
       *新的群主
       * </pre>
       *
       * <code>optional string new_group_owner = 2;</code>
       */
      public Builder setNewGroupOwner(
          String value) {
        copyOnWrite();
        instance.setNewGroupOwner(value);
        return this;
      }
      /**
       * <pre>
       *新的群主
       * </pre>
       *
       * <code>optional string new_group_owner = 2;</code>
       */
      public Builder clearNewGroupOwner() {
        copyOnWrite();
        instance.clearNewGroupOwner();
        return this;
      }
      /**
       * <pre>
       *新的群主
       * </pre>
       *
       * <code>optional string new_group_owner = 2;</code>
       */
      public Builder setNewGroupOwnerBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNewGroupOwnerBytes(value);
        return this;
      }

      /**
       * <pre>
       *是否关闭群聊邀请 true：打开 false：关闭
       * </pre>
       *
       * <code>optional bool close_invite_group_chat = 3;</code>
       */
      public boolean getCloseInviteGroupChat() {
        return instance.getCloseInviteGroupChat();
      }
      /**
       * <pre>
       *是否关闭群聊邀请 true：打开 false：关闭
       * </pre>
       *
       * <code>optional bool close_invite_group_chat = 3;</code>
       */
      public Builder setCloseInviteGroupChat(boolean value) {
        copyOnWrite();
        instance.setCloseInviteGroupChat(value);
        return this;
      }
      /**
       * <pre>
       *是否关闭群聊邀请 true：打开 false：关闭
       * </pre>
       *
       * <code>optional bool close_invite_group_chat = 3;</code>
       */
      public Builder clearCloseInviteGroupChat() {
        copyOnWrite();
        instance.clearCloseInviteGroupChat();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:site.ApiGroupUpdateProfileRequest)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApiGroupUpdateProfileRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApiGroupUpdateProfileRequest other = (ApiGroupUpdateProfileRequest) arg1;
          profile_ = visitor.visitMessage(profile_, other.profile_);
          newGroupOwner_ = visitor.visitString(!newGroupOwner_.isEmpty(), newGroupOwner_,
              !other.newGroupOwner_.isEmpty(), other.newGroupOwner_);
          closeInviteGroupChat_ = visitor.visitBoolean(closeInviteGroupChat_ != false, closeInviteGroupChat_,
              other.closeInviteGroupChat_ != false, other.closeInviteGroupChat_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  com.windchat.proto.core.GroupProto.GroupProfile.Builder subBuilder = null;
                  if (profile_ != null) {
                    subBuilder = profile_.toBuilder();
                  }
                  profile_ = input.readMessage(com.windchat.proto.core.GroupProto.GroupProfile.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(profile_);
                    profile_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  newGroupOwner_ = s;
                  break;
                }
                case 24: {

                  closeInviteGroupChat_ = input.readBool();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApiGroupUpdateProfileRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:site.ApiGroupUpdateProfileRequest)
    private static final ApiGroupUpdateProfileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApiGroupUpdateProfileRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApiGroupUpdateProfileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApiGroupUpdateProfileRequest> PARSER;

    public static com.google.protobuf.Parser<ApiGroupUpdateProfileRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ApiGroupUpdateProfileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiGroupUpdateProfileResponse)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code site.ApiGroupUpdateProfileResponse}
   */
  public  static final class ApiGroupUpdateProfileResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ApiGroupUpdateProfileResponse, ApiGroupUpdateProfileResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:site.ApiGroupUpdateProfileResponse)
      ApiGroupUpdateProfileResponseOrBuilder {
    private ApiGroupUpdateProfileResponse() {
    }
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    public static ApiGroupUpdateProfileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiGroupUpdateProfileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiGroupUpdateProfileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiGroupUpdateProfileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiGroupUpdateProfileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiGroupUpdateProfileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiGroupUpdateProfileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApiGroupUpdateProfileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiGroupUpdateProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiGroupUpdateProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApiGroupUpdateProfileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code site.ApiGroupUpdateProfileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApiGroupUpdateProfileResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiGroupUpdateProfileResponse)
        ApiGroupUpdateProfileResponseOrBuilder {
      // Construct using com.windchat.proto.server.ApiGroupUpdateProfileProto.ApiGroupUpdateProfileResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:site.ApiGroupUpdateProfileResponse)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApiGroupUpdateProfileResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApiGroupUpdateProfileResponse other = (ApiGroupUpdateProfileResponse) arg1;
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApiGroupUpdateProfileResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:site.ApiGroupUpdateProfileResponse)
    private static final ApiGroupUpdateProfileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApiGroupUpdateProfileResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApiGroupUpdateProfileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApiGroupUpdateProfileResponse> PARSER;

    public static com.google.protobuf.Parser<ApiGroupUpdateProfileResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
