// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/api_group_addMember.proto

package com.windchat.proto.server;

public final class ApiGroupAddMemberProto {
  private ApiGroupAddMemberProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ApiGroupAddMemberRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiGroupAddMemberRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    String getGroupId();
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    java.util.List<String>
        getUserListList();
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    int getUserListCount();
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    String getUserList(int index);
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserListBytes(int index);
  }
  /**
   * Protobuf type {@code site.ApiGroupAddMemberRequest}
   */
  public  static final class ApiGroupAddMemberRequest extends
      com.google.protobuf.GeneratedMessageLite<
          ApiGroupAddMemberRequest, ApiGroupAddMemberRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:site.ApiGroupAddMemberRequest)
      ApiGroupAddMemberRequestOrBuilder {
    private ApiGroupAddMemberRequest() {
      groupId_ = "";
      userList_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    private int bitField0_;
    public static final int GROUP_ID_FIELD_NUMBER = 1;
    private String groupId_;
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    public String getGroupId() {
      return groupId_;
    }
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(groupId_);
    }
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    private void setGroupId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      groupId_ = value;
    }
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    private void clearGroupId() {

      groupId_ = getDefaultInstance().getGroupId();
    }
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    private void setGroupIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      groupId_ = value.toStringUtf8();
    }

    public static final int USER_LIST_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<String> userList_;
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    public java.util.List<String> getUserListList() {
      return userList_;
    }
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    public int getUserListCount() {
      return userList_.size();
    }
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    public String getUserList(int index) {
      return userList_.get(index);
    }
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserListBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          userList_.get(index));
    }
    private void ensureUserListIsMutable() {
      if (!userList_.isModifiable()) {
        userList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(userList_);
       }
    }
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    private void setUserList(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUserListIsMutable();
      userList_.set(index, value);
    }
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    private void addUserList(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUserListIsMutable();
      userList_.add(value);
    }
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    private void addAllUserList(
        Iterable<String> values) {
      ensureUserListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, userList_);
    }
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    private void clearUserList() {
      userList_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string user_list = 2;</code>
     */
    private void addUserListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureUserListIsMutable();
      userList_.add(value.toStringUtf8());
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!groupId_.isEmpty()) {
        output.writeString(1, getGroupId());
      }
      for (int i = 0; i < userList_.size(); i++) {
        output.writeString(2, userList_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!groupId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getGroupId());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < userList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(userList_.get(i));
        }
        size += dataSize;
        size += 1 * getUserListList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ApiGroupAddMemberRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiGroupAddMemberRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiGroupAddMemberRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiGroupAddMemberRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiGroupAddMemberRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiGroupAddMemberRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiGroupAddMemberRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApiGroupAddMemberRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiGroupAddMemberRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiGroupAddMemberRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApiGroupAddMemberRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code site.ApiGroupAddMemberRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApiGroupAddMemberRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiGroupAddMemberRequest)
        ApiGroupAddMemberRequestOrBuilder {
      // Construct using com.windchat.proto.server.ApiGroupAddMemberProto.ApiGroupAddMemberRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public String getGroupId() {
        return instance.getGroupId();
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        return instance.getGroupIdBytes();
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public Builder setGroupId(
          String value) {
        copyOnWrite();
        instance.setGroupId(value);
        return this;
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public Builder clearGroupId() {
        copyOnWrite();
        instance.clearGroupId();
        return this;
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGroupIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string user_list = 2;</code>
       */
      public java.util.List<String>
          getUserListList() {
        return java.util.Collections.unmodifiableList(
            instance.getUserListList());
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string user_list = 2;</code>
       */
      public int getUserListCount() {
        return instance.getUserListCount();
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string user_list = 2;</code>
       */
      public String getUserList(int index) {
        return instance.getUserList(index);
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string user_list = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserListBytes(int index) {
        return instance.getUserListBytes(index);
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string user_list = 2;</code>
       */
      public Builder setUserList(
          int index, String value) {
        copyOnWrite();
        instance.setUserList(index, value);
        return this;
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string user_list = 2;</code>
       */
      public Builder addUserList(
          String value) {
        copyOnWrite();
        instance.addUserList(value);
        return this;
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string user_list = 2;</code>
       */
      public Builder addAllUserList(
          Iterable<String> values) {
        copyOnWrite();
        instance.addAllUserList(values);
        return this;
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string user_list = 2;</code>
       */
      public Builder clearUserList() {
        copyOnWrite();
        instance.clearUserList();
        return this;
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string user_list = 2;</code>
       */
      public Builder addUserListBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addUserListBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:site.ApiGroupAddMemberRequest)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApiGroupAddMemberRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          userList_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApiGroupAddMemberRequest other = (ApiGroupAddMemberRequest) arg1;
          groupId_ = visitor.visitString(!groupId_.isEmpty(), groupId_,
              !other.groupId_.isEmpty(), other.groupId_);
          userList_= visitor.visitList(userList_, other.userList_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  groupId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();
                  if (!userList_.isModifiable()) {
                    userList_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(userList_);
                  }
                  userList_.add(s);
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApiGroupAddMemberRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:site.ApiGroupAddMemberRequest)
    private static final ApiGroupAddMemberRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApiGroupAddMemberRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApiGroupAddMemberRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApiGroupAddMemberRequest> PARSER;

    public static com.google.protobuf.Parser<ApiGroupAddMemberRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ApiGroupAddMemberResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiGroupAddMemberResponse)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code site.ApiGroupAddMemberResponse}
   */
  public  static final class ApiGroupAddMemberResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ApiGroupAddMemberResponse, ApiGroupAddMemberResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:site.ApiGroupAddMemberResponse)
      ApiGroupAddMemberResponseOrBuilder {
    private ApiGroupAddMemberResponse() {
    }
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    public static ApiGroupAddMemberResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiGroupAddMemberResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiGroupAddMemberResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ApiGroupAddMemberResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ApiGroupAddMemberResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiGroupAddMemberResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiGroupAddMemberResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ApiGroupAddMemberResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ApiGroupAddMemberResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ApiGroupAddMemberResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApiGroupAddMemberResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code site.ApiGroupAddMemberResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ApiGroupAddMemberResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiGroupAddMemberResponse)
        ApiGroupAddMemberResponseOrBuilder {
      // Construct using com.windchat.proto.server.ApiGroupAddMemberProto.ApiGroupAddMemberResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:site.ApiGroupAddMemberResponse)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ApiGroupAddMemberResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ApiGroupAddMemberResponse other = (ApiGroupAddMemberResponse) arg1;
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ApiGroupAddMemberResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:site.ApiGroupAddMemberResponse)
    private static final ApiGroupAddMemberResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApiGroupAddMemberResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ApiGroupAddMemberResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApiGroupAddMemberResponse> PARSER;

    public static com.google.protobuf.Parser<ApiGroupAddMemberResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
