// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/im_site_auth.proto

package com.windchat.proto.server;

public final class ImSiteAuthProto {
  private ImSiteAuthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ImSiteAuthRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ImSiteAuthRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *用户个人ID
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    String getSiteUserId();
    /**
     * <pre>
     *用户个人ID
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSiteUserIdBytes();

    /**
     * <pre>
     *用户认证sessionID
     * </pre>
     *
     * <code>optional string site_session_id = 2;</code>
     */
    String getSiteSessionId();
    /**
     * <pre>
     *用户认证sessionID
     * </pre>
     *
     * <code>optional string site_session_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getSiteSessionIdBytes();
  }
  /**
   * Protobuf type {@code site.ImSiteAuthRequest}
   */
  public  static final class ImSiteAuthRequest extends
      com.google.protobuf.GeneratedMessageLite<
          ImSiteAuthRequest, ImSiteAuthRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:site.ImSiteAuthRequest)
      ImSiteAuthRequestOrBuilder {
    private ImSiteAuthRequest() {
      siteUserId_ = "";
      siteSessionId_ = "";
    }
    public static final int SITE_USER_ID_FIELD_NUMBER = 1;
    private String siteUserId_;
    /**
     * <pre>
     *用户个人ID
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    public String getSiteUserId() {
      return siteUserId_;
    }
    /**
     * <pre>
     *用户个人ID
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSiteUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(siteUserId_);
    }
    /**
     * <pre>
     *用户个人ID
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    private void setSiteUserId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      siteUserId_ = value;
    }
    /**
     * <pre>
     *用户个人ID
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    private void clearSiteUserId() {

      siteUserId_ = getDefaultInstance().getSiteUserId();
    }
    /**
     * <pre>
     *用户个人ID
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    private void setSiteUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      siteUserId_ = value.toStringUtf8();
    }

    public static final int SITE_SESSION_ID_FIELD_NUMBER = 2;
    private String siteSessionId_;
    /**
     * <pre>
     *用户认证sessionID
     * </pre>
     *
     * <code>optional string site_session_id = 2;</code>
     */
    public String getSiteSessionId() {
      return siteSessionId_;
    }
    /**
     * <pre>
     *用户认证sessionID
     * </pre>
     *
     * <code>optional string site_session_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSiteSessionIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(siteSessionId_);
    }
    /**
     * <pre>
     *用户认证sessionID
     * </pre>
     *
     * <code>optional string site_session_id = 2;</code>
     */
    private void setSiteSessionId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      siteSessionId_ = value;
    }
    /**
     * <pre>
     *用户认证sessionID
     * </pre>
     *
     * <code>optional string site_session_id = 2;</code>
     */
    private void clearSiteSessionId() {

      siteSessionId_ = getDefaultInstance().getSiteSessionId();
    }
    /**
     * <pre>
     *用户认证sessionID
     * </pre>
     *
     * <code>optional string site_session_id = 2;</code>
     */
    private void setSiteSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      siteSessionId_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!siteUserId_.isEmpty()) {
        output.writeString(1, getSiteUserId());
      }
      if (!siteSessionId_.isEmpty()) {
        output.writeString(2, getSiteSessionId());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!siteUserId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSiteUserId());
      }
      if (!siteSessionId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getSiteSessionId());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ImSiteAuthRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ImSiteAuthRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ImSiteAuthRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ImSiteAuthRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ImSiteAuthRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ImSiteAuthRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ImSiteAuthRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ImSiteAuthRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ImSiteAuthRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ImSiteAuthRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImSiteAuthRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code site.ImSiteAuthRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ImSiteAuthRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ImSiteAuthRequest)
        ImSiteAuthRequestOrBuilder {
      // Construct using com.windchat.proto.server.ImSiteAuthProto.ImSiteAuthRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *用户个人ID
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public String getSiteUserId() {
        return instance.getSiteUserId();
      }
      /**
       * <pre>
       *用户个人ID
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSiteUserIdBytes() {
        return instance.getSiteUserIdBytes();
      }
      /**
       * <pre>
       *用户个人ID
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder setSiteUserId(
          String value) {
        copyOnWrite();
        instance.setSiteUserId(value);
        return this;
      }
      /**
       * <pre>
       *用户个人ID
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder clearSiteUserId() {
        copyOnWrite();
        instance.clearSiteUserId();
        return this;
      }
      /**
       * <pre>
       *用户个人ID
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder setSiteUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSiteUserIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *用户认证sessionID
       * </pre>
       *
       * <code>optional string site_session_id = 2;</code>
       */
      public String getSiteSessionId() {
        return instance.getSiteSessionId();
      }
      /**
       * <pre>
       *用户认证sessionID
       * </pre>
       *
       * <code>optional string site_session_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSiteSessionIdBytes() {
        return instance.getSiteSessionIdBytes();
      }
      /**
       * <pre>
       *用户认证sessionID
       * </pre>
       *
       * <code>optional string site_session_id = 2;</code>
       */
      public Builder setSiteSessionId(
          String value) {
        copyOnWrite();
        instance.setSiteSessionId(value);
        return this;
      }
      /**
       * <pre>
       *用户认证sessionID
       * </pre>
       *
       * <code>optional string site_session_id = 2;</code>
       */
      public Builder clearSiteSessionId() {
        copyOnWrite();
        instance.clearSiteSessionId();
        return this;
      }
      /**
       * <pre>
       *用户认证sessionID
       * </pre>
       *
       * <code>optional string site_session_id = 2;</code>
       */
      public Builder setSiteSessionIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSiteSessionIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:site.ImSiteAuthRequest)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ImSiteAuthRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ImSiteAuthRequest other = (ImSiteAuthRequest) arg1;
          siteUserId_ = visitor.visitString(!siteUserId_.isEmpty(), siteUserId_,
              !other.siteUserId_.isEmpty(), other.siteUserId_);
          siteSessionId_ = visitor.visitString(!siteSessionId_.isEmpty(), siteSessionId_,
              !other.siteSessionId_.isEmpty(), other.siteSessionId_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  siteUserId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  siteSessionId_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ImSiteAuthRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:site.ImSiteAuthRequest)
    private static final ImSiteAuthRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImSiteAuthRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ImSiteAuthRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ImSiteAuthRequest> PARSER;

    public static com.google.protobuf.Parser<ImSiteAuthRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ImSiteAuthResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ImSiteAuthResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *服务站点的地址
     * </pre>
     *
     * <code>optional string site_server = 1;</code>
     */
    String getSiteServer();
    /**
     * <pre>
     *服务站点的地址
     * </pre>
     *
     * <code>optional string site_server = 1;</code>
     */
    com.google.protobuf.ByteString
        getSiteServerBytes();
  }
  /**
   * Protobuf type {@code site.ImSiteAuthResponse}
   */
  public  static final class ImSiteAuthResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ImSiteAuthResponse, ImSiteAuthResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:site.ImSiteAuthResponse)
      ImSiteAuthResponseOrBuilder {
    private ImSiteAuthResponse() {
      siteServer_ = "";
    }
    public static final int SITE_SERVER_FIELD_NUMBER = 1;
    private String siteServer_;
    /**
     * <pre>
     *服务站点的地址
     * </pre>
     *
     * <code>optional string site_server = 1;</code>
     */
    public String getSiteServer() {
      return siteServer_;
    }
    /**
     * <pre>
     *服务站点的地址
     * </pre>
     *
     * <code>optional string site_server = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSiteServerBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(siteServer_);
    }
    /**
     * <pre>
     *服务站点的地址
     * </pre>
     *
     * <code>optional string site_server = 1;</code>
     */
    private void setSiteServer(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      siteServer_ = value;
    }
    /**
     * <pre>
     *服务站点的地址
     * </pre>
     *
     * <code>optional string site_server = 1;</code>
     */
    private void clearSiteServer() {

      siteServer_ = getDefaultInstance().getSiteServer();
    }
    /**
     * <pre>
     *服务站点的地址
     * </pre>
     *
     * <code>optional string site_server = 1;</code>
     */
    private void setSiteServerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      siteServer_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!siteServer_.isEmpty()) {
        output.writeString(1, getSiteServer());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!siteServer_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSiteServer());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ImSiteAuthResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ImSiteAuthResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ImSiteAuthResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ImSiteAuthResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ImSiteAuthResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ImSiteAuthResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ImSiteAuthResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ImSiteAuthResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ImSiteAuthResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ImSiteAuthResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImSiteAuthResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code site.ImSiteAuthResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ImSiteAuthResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ImSiteAuthResponse)
        ImSiteAuthResponseOrBuilder {
      // Construct using com.windchat.proto.server.ImSiteAuthProto.ImSiteAuthResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *服务站点的地址
       * </pre>
       *
       * <code>optional string site_server = 1;</code>
       */
      public String getSiteServer() {
        return instance.getSiteServer();
      }
      /**
       * <pre>
       *服务站点的地址
       * </pre>
       *
       * <code>optional string site_server = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSiteServerBytes() {
        return instance.getSiteServerBytes();
      }
      /**
       * <pre>
       *服务站点的地址
       * </pre>
       *
       * <code>optional string site_server = 1;</code>
       */
      public Builder setSiteServer(
          String value) {
        copyOnWrite();
        instance.setSiteServer(value);
        return this;
      }
      /**
       * <pre>
       *服务站点的地址
       * </pre>
       *
       * <code>optional string site_server = 1;</code>
       */
      public Builder clearSiteServer() {
        copyOnWrite();
        instance.clearSiteServer();
        return this;
      }
      /**
       * <pre>
       *服务站点的地址
       * </pre>
       *
       * <code>optional string site_server = 1;</code>
       */
      public Builder setSiteServerBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSiteServerBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:site.ImSiteAuthResponse)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ImSiteAuthResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ImSiteAuthResponse other = (ImSiteAuthResponse) arg1;
          siteServer_ = visitor.visitString(!siteServer_.isEmpty(), siteServer_,
              !other.siteServer_.isEmpty(), other.siteServer_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  siteServer_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ImSiteAuthResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:site.ImSiteAuthResponse)
    private static final ImSiteAuthResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImSiteAuthResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ImSiteAuthResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ImSiteAuthResponse> PARSER;

    public static com.google.protobuf.Parser<ImSiteAuthResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
